---
output:
  html_document:
    includes:
      in_header: "header/usgs_in_header.html"
      before_body: "header/usgs_before_body.html"
      after_body: "footer/usgs_after_body.html"
    self_contained: no
      
    
---

Last updated `r Sys.time()` CDT


```{r, include=FALSE}
library(soilmoisturetools)
library(dplyr)

key_metadata = c('station', 'latitude', 'longitude', 'name')

#load a bunch of data
ok     = to_hist_percentile(ok_data())
ok_met = ok_sites_metadata(ok$station)

tx     = to_hist_percentile(tx_data())
tx_met = tx_sites_metadata(tx$station)

crn    = to_hist_percentile(crn_data())
crn_met= crn_sites_metadata(crn$station)

#scan_sites = scan_sites_by_element_code("SMS")
#scan_met   = scan_sites_metadata(scan_sites)
#scan_met$station = scan_met$stationTriplet

#scan_2 = to_hist_percentile(scan_data(scan_sites, -2, start = Sys.Date()-as.difftime(2, units='hours')))
#scan_8 = to_hist_percentile(scan_data(scan_sites, -8, start = Sys.Date()-as.difftime(2, units='hours')))
#scan_20= to_hist_percentile(scan_data(scan_sites, -20, start = Sys.Date()-as.difftime(2, units='hours')))


ok_met = ok_met[, key_metadata]
tx_met = tx_met[, key_metadata]
#scan_met = scan_met[, key_metadata]
crn_met  = crn_met[, key_metadata]

data = rbind(tx, ok, crn)#, scan_2, scan_8, scan_20)
metadata = rbind(tx_met, ok_met, 
								 #left_join(scan_2, scan_met)[, key_metadata], 
								 #left_join(scan_8, scan_met)[, key_metadata], 
								 #left_join(scan_20, scan_met)[, key_metadata], 
								 crn_met)

##Doing this based on instruction from Partha
data$value[data$value < 0 & data$value > -30] = 0
data$value[data$value > 100 & data$value < 130] = 100
data$value[data$value > 130 | data$value < -30] = NA

```


## 0-10cm

```{r, echo=FALSE, warning=FALSE, fig.align='center'}

depth_i = data$depth_cm > 0 & data$depth_cm < 10

moisture_map(data[depth_i, ], 
						 metadata[depth_i, ],
						 out_file=NULL)


```

## 10-30cm

```{r, echo=FALSE, warning=FALSE, fig.align='center'}

depth_i = data$depth_cm > 10 & data$depth_cm < 30

moisture_map(data[depth_i, ], 
						 metadata[depth_i, ],
						 out_file=NULL)


```

## 30-100 cm

```{r, echo=FALSE, warning=FALSE, fig.align='center'}

depth_i = data$depth_cm > 30 & data$depth_cm < 100

moisture_map(data[depth_i, ], 
						 metadata[depth_i, ],
						 out_file=NULL)


```
